### PR TITLE
Update code and indicators ids following changes from David

### PR DESCRIPTION
**Pull request by simaob**
This is not to be merged, but to be tested on staging. I've been deploying from this branch directly to staging so as not to mess up the deployable code.

### CODE REVIEW

**Comment by simaob** [comment]
Hi @j8seangel this is now ready to be reviewed and then merged to develop -> staging -> master. =) Could you have a look see if it's not breaking? It updates the country pages with new data.

**Comment by j8seangel** [comment]
Going to staging now!

**Comment by j8seangel** [comment]
Tested, fixed and going to production now!

**Comment by j8seangel** [comment]
Working on production 🎉

**Comment by simaob** [comment]
Thanks, José!! =)

**Pull request merged**
