### PR TITLE
Feature/data download page

### PR DESCRIPTION
**Pull request by j8seangel**
This PR includes the UI to generate the url for download data:

kapture 2017-07-10 at 19 56 56

### CODE REVIEW

**Comment by j8seangel** [comment]
This is ready! however, I'm getting an error in the API that we could fix that in its branch (https://github.com/Vizzuality/gfw-climate/pull/402) 

Please review it and let me know.

**Comment by agnessa** [comment]
Can we have `jurisdiction_ids` and `indicators_ids` as arrays of integers rather than names please? (the same would apply to `area_ids` but it seems we don't have areas here anyway).

The Carto DB query fails with a SyntaxError because of these; I'll add some exception handling to the backend so that it does not end up with error 500 in such case, but this needs to be amended as well.

**Comment by simaob** [comment]
@j8seangel can you check what Agnieszka said? Thanks!

**Comment by j8seangel** [comment]
Fixed!

**Comment by agnessa** [comment]
Thanks, works now! 👍

**Comment by simaob** [comment]
Replaced by this rebased PR: https://github.com/Vizzuality/gfw-climate/pull/414

**Pull request closed without merging**
