### PR TITLE
Feature/new modals

### PR DESCRIPTION
**Pull request by mbarrenechea**
It would be great if we merge all the modals to this ones, that are independents.

### CODE REVIEW

**Comment by mbarrenechea** [comment]
We must finish entering content. (see '####### TABLE #######') => app/views/shared/_sources_widgets.html.erb

**Comment by simaob** [comment]
OK! =) Noted.

**Comment by simaob** [comment]
@apercas any idea what's the state of this? Is it just the data missing for the tables?

**Comment by mbarrenechea** [comment]
Hey, yes we need to fill all the content before merge it.

**Comment by simaob** [comment]
OK. I can do that maybe =)

**Comment by mbarrenechea** [comment]
Let me prepare one table and you will copy the structure.

**Comment by simaob** [comment]
:+1:

**Pull request merged**
