### PR TITLE
Nightly version is the correct one for develop

### PR DESCRIPTION
**Pull request by mbarrenechea**
@simaob @geriux set this var on your .env file:
## **LOCAL**
'GFW_ASSETS_URL=http://gfw-assets.s3.amazonaws.com/static/gfw-assets.nightly.js'

## **STAGING**
I've already changed the env var in heroku (staging). 

## **PRO**
Please, **don't merge** this with master until I confirm you to do it
I don't have access to the PRO environment but you Simao should set the config var to this:
'GFW_ASSETS_URL=http://gfw-assets.s3.amazonaws.com/static/gfw-assets.latest.js'

As I did with the GFW team, here you have some documentation related to this:
https://docs.google.com/a/vizzuality.com/document/d/1m_v-L7WVmDlBhd5eGhnpmHPTmaQ8c7gVvwUTaJweVv4/edit?usp=sharing

### CODE REVIEW

**Comment by simaob** [comment]
I've added you to the production application with your Vizzuality's email.

I might not merge this until it's good to merge to production as we are merging a few features that we will want in Production.

**Comment by simaob** [comment]
Would that break anything?

**Comment by mbarrenechea** [comment]
No it wouldn't. As long as you don't deploy the gfw-assets fix that I've just made. Even if you do that, nothing will break, but the new menu doesn't have green light to be deployed to PRO (that's the reason).

FYI, I have just created this config var in PRO app.

**Comment by simaob** [comment]
@mbarrenechea what's the status of the new menu? has it been decided and approved? Shall I merge this?

**Comment by mbarrenechea** [comment]
The nightly version should be on all staging sites. See this doc => https://docs.google.com/document/d/1m_v-L7WVmDlBhd5eGhnpmHPTmaQ8c7gVvwUTaJweVv4/edit?usp=sharing 

The latest version should be on all production sites, but we need to wait a few days. this week we are going to deploy it. I will do a PR when it's ready

**Comment by mbarrenechea** [comment]
Sorry, answering your question: yes, you can merge this as long as you don't deploy it to production, only staging

**Comment by geriux** [comment]
Hi! I think it can be deployed to production since you added the ENV variable as latest on prod so it should work ok, right @mbarrenechea ??

**Comment by mbarrenechea** [comment]
Yes, sorry

**Pull request merged**
