### PR TITLE
Feature/indicators

### PR DESCRIPTION
**Pull request by rschumann**
Before merge we need to complete the indicators groups under config/json/widgets.js

### CODE REVIEW

**Comment by simaob** [comment]
Instead of manually updating the widgets.json file I think we should use this table from CartoDB: https://wri-01.cartodb.com/tables/indicators . This table will have the list of all available indicators, and we can group it by indicator_group, to generate a similar json to the one that is currently in widgets.json. This makes it more dynamic and easier to maintain. As an extra I can add the type of chart in there as well, so that we get the complete set of data.

We can then use caching in rails to avoid generating it with each access.

What do you think @rschumann?

**Comment by rschumann** [comment]
We can think about different ways to manage this info, but for now, for development is a really good alternative. Any developer should be able to update this information quickly without to have to edit data in the DB.

**Comment by simaob** [comment]
Yeah I agree that having a mock file with the indicators is a good way to get development of the front end going. But now we already have some data on CartoDB and are about to get more, so might be worth updating the index action of the indicators endpoint to respond with a similar format of the widgets.json, no? So that the sawp can be easily made?

For me to update the widgets.json I have one question: what are the ids in the current widgets.json file based on? Are they real ids from cartoDb? Or are they linked to some other file?

Thanks!

**Comment by rschumann** [comment]
Yes the ids for indicators are real indicators from cartoDB.

**Pull request merged**
