### PR TITLE
Feature/analysis

### PR DESCRIPTION
**Pull request by mbarrenechea**
Right now, the analysis isn't filtering by years, so we need to deploy the API with the work of Alicia.

### CODE REVIEW

**Comment by simaob** [comment]
Is it normal that it times out?

**Comment by simaob** [comment]
Could you use the list of countries that is used in the countries index page?

**Comment by mbarrenechea** [comment]
Ok, service created to get only the active countries. Ready to merge, once the API is deployed

**Comment by simaob** [comment]
Cheers.

@aagm & @apercas: Any idea when the API will be deployed? =)

**Comment by apercas** [comment]
I'll be deploying over today, but I'm working on regular GFW

**Comment by simaob** [comment]
OK. Please nudge me when you do, so I can do the same with Climate.
Thanks!

**Comment by apercas** [comment]
I will!

**Comment by simaob** [comment]
Only one comment on this: Wasn't there a way to go to the Country's Profile from the analysis panel? I thought it was in the designs.

OTher than that it looks great! =)

<lame>
And if I was Adrián I would say:

Eres el amo puto!
</lame>
</terrible_joke>

https://s-media-cache-ak0.pinimg.com/736x/89/4d/21/894d2174d3a1f73228305a5b955440c6.jpg

**Comment by apercas** [comment]
xD

**Comment by mbarrenechea** [comment]
Yes of course. Give 5 minutes

**Comment by mbarrenechea** [comment]
Ready to merge

**Comment by simaob** [comment]
:tada:

**Pull request merged**
