### PR TITLE
Feature/dark basemap custom labels

### PR DESCRIPTION
**Pull request by j8seangel**
Add a custom layer when the basemap is 'dark' for the labels as the image:
image

Not merge until @aagm finish the styles in the named map.

### CODE REVIEW

**Comment by simaob** [comment]
@aagm Now there's a bit of duplication in the labels. Is there a way to disable the labels from the dark matter and just show the ones you added?

Image for reference:

screen shot 2016-10-18 at 09 54 59

**Comment by j8seangel** [comment]
Yes, don't worry about that because she told me it is not finished yet and she will fix it so that is why we can't merge until she finish.

**Comment by aagm** [comment]
hey! Yeah to be able to replicate the styles from dark matter, i need a couple of labels that are giving trouble. there's seems to be a bug related some of them and i'm pending answer from carto side.

**Comment by aagm** [comment]
Good news everyone! the first version of this is ready to go live!

**Pull request merged**
