### PR TITLE
Insights - Glad Alerts Visualization UI tweaks and data from API

### PR DESCRIPTION
**Pull request by geriux**
- Added new labels in the graph and removed some from the legend.
- Now the data is loaded from the new API (datasets will change soon, it'll be just an ID change).
- Metadata added.
- Text changes.

screen shot 2016-07-19 at 17 33 08

### CODE REVIEW

**Comment by simaob** [comment]
This looks good, @geriux. Could you just make sure that all the 2s in CO2 are underscript? Thanks!

**Comment by geriux** [comment]
Ok! I'll work on it, it might take just a bit to do it the right way, since its' a SVG text we have to append it with tspans to style each part differently.

**Comment by simaob** [comment]
OK! thanks! =)

**Comment by geriux** [comment]
Added support for underscript text in the labels =)

**Comment by simaob** [comment]
I might sound picky... or maybe I'm really picky... but you missed a small spot:

screen shot 2016-07-20 at 10 54 18

**Comment by geriux** [comment]
My bad! Sorry, fixed!

**Pull request merged**
