### PR TITLE
Fix - Widgets - SVG icons

### PR DESCRIPTION
**Pull request by geriux**
- Solves the issue with Firefox v.44 and posible other browsers.

### CODE REVIEW

**Comment by simaob** [comment]
Would this be easy enough to apply to the WorldBank project (https://github.com/Vizzuality/WorldBankAsia)? I'm having the same issue there.

**Comment by simaob** [comment]
Some svgs still have the issue ,maybe they are defined in some other place? (check screenshot).

screen shot 2016-03-21 at 15 46 45

**Comment by geriux** [comment]
My bad! Thought this was happening only here. I'll check all SVG icons.

**Comment by geriux** [comment]
This should be fixed now, regarding to your WB project question, it depends on the CSS code and how it's structured and also the amount of SVG icons to check. But it shouldn't take much time :)

**Comment by simaob** [comment]
Cool, I'll have a look! =)

OK, I might add a task for that. It really gets to my nervous as my browser of choice is firefox :p I look at our projects and the svgs are broken I feel sad :p

**Pull request merged**
